//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RibbonFileManager.Adapters
{
    
    public class IHostContractToViewAddInAdapter : RibbonFileManager.Views.IHost
    {
        private Start9.Api.Contracts.IHostContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IHostContractToViewAddInAdapter()
        {
        }
        public IHostContractToViewAddInAdapter(Start9.Api.Contracts.IHostContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public void SendMessage(RibbonFileManager.Views.IMessage message)
        {
            _contract.SendMessage(RibbonFileManager.Adapters.IMessageAddInAdapter.ViewToContractAdapter(message));
        }
        public void SaveConfiguration(RibbonFileManager.Views.IModule module)
        {
            _contract.SaveConfiguration(RibbonFileManager.Adapters.IModuleAddInAdapter.ViewToContractAdapter(module));
        }
        public System.Collections.Generic.IList<RibbonFileManager.Views.IModule> GetModules()
        {
            return System.AddIn.Pipeline.CollectionAdapters.ToIList<Start9.Api.Contracts.IModuleContract, RibbonFileManager.Views.IModule>(_contract.GetModules(), RibbonFileManager.Adapters.IModuleAddInAdapter.ContractToViewAdapter, RibbonFileManager.Adapters.IModuleAddInAdapter.ViewToContractAdapter);
        }
        public RibbonFileManager.Views.IConfiguration GetGlobalConfiguration()
        {
            return RibbonFileManager.Adapters.IConfigurationAddInAdapter.ContractToViewAdapter(_contract.GetGlobalConfiguration());
        }
        internal Start9.Api.Contracts.IHostContract GetSourceContract()
        {
            return _contract;
        }
    }
}

