//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RibbonFileManager.Adapters
{
    
    [System.AddIn.Pipeline.AddInAdapterAttribute()]
    public class IModuleViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Start9.Api.Contracts.IModuleContract
    {
        private RibbonFileManager.Views.IModule _view;
        public IModuleViewToContractAddInAdapter(RibbonFileManager.Views.IModule view)
        {
            _view = view;
        }
        public Start9.Api.Contracts.IConfigurationContract Configuration
        {
            get
            {
                return RibbonFileManager.Adapters.IConfigurationAddInAdapter.ViewToContractAdapter(_view.Configuration);
            }
        }
        public Start9.Api.Contracts.IMessageContractContract MessageContract
        {
            get
            {
                return RibbonFileManager.Adapters.IMessageContractAddInAdapter.ViewToContractAdapter(_view.MessageContract);
            }
        }
        public Start9.Api.Contracts.IReceiverContractContract ReceiverContract
        {
            get
            {
                return RibbonFileManager.Adapters.IReceiverContractAddInAdapter.ViewToContractAdapter(_view.ReceiverContract);
            }
        }
        public virtual void Initialize(Start9.Api.Contracts.IHostContract host)
        {
            _view.Initialize(RibbonFileManager.Adapters.IHostAddInAdapter.ContractToViewAdapter(host));
        }
        internal RibbonFileManager.Views.IModule GetSourceView()
        {
            return _view;
        }
    }
}

