//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RibbonFileManager.Adapters
{
    
    public class IReceiverContractAddInAdapter
    {
        internal static RibbonFileManager.Views.IReceiverContract ContractToViewAdapter(Start9.Api.Contracts.IReceiverContractContract contract)
        {
            if ((contract == null))
            {
                return null;
            }
            if (((System.Runtime.Remoting.RemotingServices.IsObjectOutOfAppDomain(contract) != true) 
                        && contract.GetType().Equals(typeof(IReceiverContractViewToContractAddInAdapter))))
            {
                return ((IReceiverContractViewToContractAddInAdapter)(contract)).GetSourceView();
            }
            else
            {
                return new IReceiverContractContractToViewAddInAdapter(contract);
            }
        }
        internal static Start9.Api.Contracts.IReceiverContractContract ViewToContractAdapter(RibbonFileManager.Views.IReceiverContract view)
        {
            if ((view == null))
            {
                return null;
            }
            if (view.GetType().Equals(typeof(IReceiverContractContractToViewAddInAdapter)))
            {
                return ((IReceiverContractContractToViewAddInAdapter)(view)).GetSourceContract();
            }
            else
            {
                return new IReceiverContractViewToContractAddInAdapter(view);
            }
        }
    }
}

