//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RibbonFileManager.Adapters
{
    
    public class IReceiverContractContractToViewAddInAdapter : RibbonFileManager.Views.IReceiverContract
    {
        private Start9.Api.Contracts.IReceiverContractContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static IReceiverContractContractToViewAddInAdapter()
        {
        }
        public IReceiverContractContractToViewAddInAdapter(Start9.Api.Contracts.IReceiverContractContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public System.Collections.Generic.IList<RibbonFileManager.Views.IReceiverEntry> Entries
        {
            get
            {
                return System.AddIn.Pipeline.CollectionAdapters.ToIList<Start9.Api.Contracts.IReceiverEntryContract, RibbonFileManager.Views.IReceiverEntry>(_contract.Entries, RibbonFileManager.Adapters.IReceiverEntryAddInAdapter.ContractToViewAdapter, RibbonFileManager.Adapters.IReceiverEntryAddInAdapter.ViewToContractAdapter);
            }
        }
        internal Start9.Api.Contracts.IReceiverContractContract GetSourceContract()
        {
            return _contract;
        }
    }
}

