//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RibbonFileManager.Adapters
{
    
    public class MessageReceivedEventArgsViewToContractAddInAdapter : System.AddIn.Pipeline.ContractBase, Start9.Api.Contracts.IMessageReceivedEventArgsContract
    {
        private RibbonFileManager.Views.MessageReceivedEventArgs _view;
        public MessageReceivedEventArgsViewToContractAddInAdapter(RibbonFileManager.Views.MessageReceivedEventArgs view)
        {
            _view = view;
        }
        public Start9.Api.Contracts.IMessageContract Message
        {
            get
            {
                return RibbonFileManager.Adapters.IMessageAddInAdapter.ViewToContractAdapter(_view.Message);
            }
        }
        internal RibbonFileManager.Views.MessageReceivedEventArgs GetSourceView()
        {
            return _view;
        }
    }
}

