//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RibbonFileManager.Adapters
{
    
    public class MessageReceivedEventArgsContractToViewAddInAdapter : RibbonFileManager.Views.MessageReceivedEventArgs
    {
        private Start9.Api.Contracts.IMessageReceivedEventArgsContract _contract;
        private System.AddIn.Pipeline.ContractHandle _handle;
        static MessageReceivedEventArgsContractToViewAddInAdapter()
        {
        }
        public MessageReceivedEventArgsContractToViewAddInAdapter(Start9.Api.Contracts.IMessageReceivedEventArgsContract contract)
        {
            _contract = contract;
            _handle = new System.AddIn.Pipeline.ContractHandle(contract);
        }
        public override RibbonFileManager.Views.IMessage Message
        {
            get
            {
                return RibbonFileManager.Adapters.IMessageAddInAdapter.ContractToViewAdapter(_contract.Message);
            }
        }
        internal Start9.Api.Contracts.IMessageReceivedEventArgsContract GetSourceContract()
        {
            return _contract;
        }
    }
}

